### ISSUE TITLE
REST-API: Invalid user id result to 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-users-resources#47]
Package version: [b9416](https://github.com/inveniosoftware/invenio-requests/commit/b0ca643ffbe6426b6a464ca0d8693d68234b9416)

## Describe the bug
Related to [46](https://github.com/inveniosoftware/invenio-users-resources/issues/46)
following the [docs](https://inveniordm.docs.cern.ch/reference/rest_api_users/#:~:text=Get%20a-,user,-%C2%B6). Using Postman:
Providing invalid user id will results to 500 internal server error
- **GET {{baseURL}}/api/users/{{user-id}}**
- **GET {{baseURL}}/api/users/{{user-id}}/avatar.svg**

## Steps to Reproduce
1. Go to Postman
2. send req from one of the endpoints above with an invalid user-id
3. See 500 error

## Expected behavior
Quit gracefully with an error message

## Screenshots 
```console
Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/samk13/dev/v9/invenio-users-resources/invenio_users_resources/resources/users/resource.py", line 59, in read
    item = self.service.read(
  File "/home/samk13/dev/v9/invenio-users-resources/invenio_users_resources/services/users/service.py", line 77, in read
    raise LookupError(f"No user with id '{id_}'.")
LookupError: No user with id 'userudapsikd'.
```

## Additional context
I would like to know if we should merge this issue with [46](https://github.com/inveniosoftware/invenio-users-resources/issues/46) or keep them separate?

**Comment by Samk13** [comment]
I will do this one, no need to assign anyone on this.
